repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: detect-private-key
      args: ['--allow-missing-credentials']

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.3
  hooks:
    - id: prettier
      name: Prettier
      description: Format code with Prettier
      entry: prettier --write --loglevel warn
      language: node
      types: [javascript, jsx, typescript, tsx, json, css, scss, html, yaml, md]
      additional_dependencies:
        - prettier@3.0.3

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0
  hooks:
    - id: eslint
      name: ESLint
      description: Lint JavaScript/TypeScript files
      entry: eslint --fix
      language: node
      types: [javascript, jsx, typescript, tsx]
      additional_dependencies:
        - eslint@8.56.0
        - eslint-plugin-security@1.7.1
        - eslint-plugin-react@7.33.2
        - eslint-config-prettier@9.1.0
        - @typescript-eslint/eslint-plugin@6.14.0
        - @typescript-eslint/parser@6.14.0

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
    - id: black
      name: Black
      description: Format Python code
      language: python
      types: [python]

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      name: Flake8
      description: Lint Python files
      language: python
      types: [python]
      additional_dependencies: ['flake8-bugbear==24.1.11', 'flake8-bandit==4.1.1']

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.8
  hooks:
    - id: ruff
      name: Ruff
      description: Fast Python linter
      args: [--fix]

- repo: local
  hooks:
    - id: security-audit
      name: Security Audit
      description: Run security checks
      entry: npm run audit
      language: node
      files: package\.json
      pass_filenames: false
      stages: [push]